# fly.toml file generated for vttmud on 2023-04-05T11:31:00+02:00

app = "vttmud"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ams"
processes = []

[env]
  PORT = "8080"

[deploy]
  release_command = "/bin/sh -c 'cd /app && /app/node_modules/.bin/node-pg-migrate up'"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
